CapstoneProject/Base/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Base import views

app_name = "Base"

urlpatterns = [
    url(r"^register/$",views.userRegister,name="register"),
    url(r"^login/$",views.userLogin,name="login"),
    url(r"^logout/$",views.userLogout,name = "logout"),
    url(r"^check/$",views.check),
    url(r"^getUserAssets/$",views.getUserAssets,name = 'getAssets'),
    url(r"^getUserLiabilities/$",views.getUserLiabilities,name = 'getLiabilities'),
    url(r'^getUserDependents/$',views.getUserDependents,name = 'getDependents'),
    url(r'^getUserIncome/$',views.getUserIncomeData,name = 'getMonthlyIncome'),
    url(r"^getRepeatingExpenseData/$",views.getUserExpenseData,name = "getRepeatingExpense"),
    url(r"^getRepeatingInvestmentData/$",views.getUserInvestmentData,name = "getRepeatingInvestment"),
    url(r"^getUserPredictionValues/$",views.getUserPredictionValues,name = "getUserPredictionData"),
    url(r"^showDisplayBoxes/$",views.showBuckets),
    url(r"^financialSecurityOverview/$",views.financialOverview)
    ]

# getUserPredictionValues

CapstoneProject/CapstoneProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from CapstoneProject import views
# from Base import views
# from HealthInsurancePredict import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.test),
    url(r'^base/', include("Base.urls")),
    url(r"^healthInsurance/",include("HealthInsurancePredict.urls")),
    url(r"^investment/",include("Investment.urls")),
    url(r"^emergency/",include("Emergency.urls")),
]

CapstoneProject/CapstoneProject/views.py
from django.shortcuts import render
from django.http import HttpResponse

def test(response):
    '''
        Returns home page
    '''
    return render(response,"CapstoneProject/index.html")

CapstoneProject/templates/CapstoneProject/index.html
{% extends "Base/getBase.html" %}
{% load static %}

{% block navbarTag %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'Base:login' %}">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'Base:register' %}"">Register</a>
    </li
{% endblock %}

{% block body_block %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      .services_offer{
        padding-bottom : 30px;
      }
      #contact_us{
        height : 50%;
        top : 50%;
        margin : auto;
      }
      #temp{
        height: 30px;
      }
    </style>

    <div class = "container" style = "width:600px;height:400px;">
      <div id="change-images" class="carousel slide  col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#change-images" data-slide-to="0" class="active"></li>
          <li data-target="#change-images" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="https://i2.cdn.turner.com/money/dam/assets/160105170314-financial-security-lock-640x360.jpg">
            <div class="carousel-caption">
              Tom
            </div>
          </div>
          <div class="item">
            <img src="https://www.goodnewspilipinas.com/wp-content/uploads/2018/03/key.jpg">
            <div class="carousel-caption">
              Family
            </div>
          </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#change-images" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#change-images" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div style = "background-color : #CC0000;color : white">
      <br><br><br>
      <div class = "container">
        <center>
          <h1>Financial Security</h1>
          <i><h3>Idealogy</h3></i>
        </center>
        <br>
        <p style = " text-align: justify;text-align-last: center;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <br><br><br>
    </div>

    <div style = "background-color : black; color : white">
      <div class="container">
        <center>
          <h1>Services We Offer</h1>
          <br><br>
        </center>
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
        <img src="{% static 'Capstone Project/coming soon.jpg' %}" class="img-circle col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4 services_offer" title = "Coming Soon">
      </div>
    </div>

    <center id = "temp">
      <div id="contact_us" class = "container">
        <i class="fa fa-facebook-official"></i>
        <i class="fa fa-instagram"></i>
        <i class="fa fa-snapchat"></i>
        <i class="fa fa-pinterest-p"></i>
        <i class="fa fa-twitter"></i>
        <i class="fa fa-linkedin"></i>
      </div>
    </center>

{% endblock %}